spring.profiles.active=@spring.profiles.active@

spring.jpa.open-in-view=false

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hybernate.jdbc.time_zone=CET
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.datasource.url=jdbc:postgresql://${deps.db.url}/${deps.db.dbname}
spring.datasource.username=${deps.db.username}
spring.datasource.password=${deps.db.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=/var/log/stimare.log

# jwt.secret deve essere almeno lunga 64 bytes
jwt.secret=dantar.secret.must-be-at-least-64-bytes-long-with-new-jjwt-lib-v0.11.0
# jwt.token.validity=8 * 60 * 60
jwt.token.validity=28800

spring.cache.cache-names=propertyCache

# spring boot:
server.port=8080
# actuator:
management.server.port=8081

# app.url=https://dove.dantar.it
app.url=
app.pictures.dir=/opt/dove/pictures