# place in /opt/swag
version: "3.5"

services:

  swag:
    image: ghcr.io/linuxserver/swag:2.5.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Rome
      - URL=rodarialtelefono.it
      - EXTRA_DOMAINS=alice.wvoce.it,play.wvoce.it,dantar.it,www.dantar.it,gogolgame.it,www.gogolgame.it,www.rodarialtelefono.it
      - VALIDATION=http
      - EMAIL=info@wvoce.it
    volumes:
      - /opt/swag/config:/config
      - /opt/rodarialtelefono.it/html:/var/www/rodarialtelefono.it:ro
      - /home/daniele/html:/var/www/daniele/html:ro
      - /home/daniele/apps/dove/docker/data/images:/opt/dove/images:ro
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]
      interval: "30s"
      timeout: "10s"
      retries: 3
    restart: unless-stopped
