# place in /opt/swag/config/nginx/proxy-confs

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    include /config/nginx/ssl.conf;
    server_name dove.dantar.it

    access_log /config/log/nginx/dantar.it.access.log;
    error_log  /config/log/nginx/dantar.it.error.log;

    location / {
        proxy_pass http://localhost:8180/;
        include /config/nginx/proxy.conf;
    }

    location /backend/ {
        proxy_pass http://localhost:8181/;
        include /config/nginx/proxy.conf;
    }

}
