ALTER TABLE oggetto
ADD COLUMN IF NOT EXISTS registrato TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS modificato TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE OR REPLACE FUNCTION aggiorna_modificato()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW IS DISTINCT FROM OLD THEN
        NEW.modificato = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_aggiorna_modificato_oggetto ON oggetto;

CREATE TRIGGER trigger_aggiorna_modificato_oggetto
BEFORE UPDATE ON oggetto
FOR EACH ROW
EXECUTE FUNCTION aggiorna_modificato();