--
-- PostgreSQL database dump
--

-- Dumped from database version 10.23 (Ubuntu 10.23-0ubuntu0.18.04.2)
-- Dumped by pg_dump version 10.23 (Ubuntu 10.23-0ubuntu0.18.04.2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: ltree; Type: EXTENSION; Schema: -; Owner: 
--

CREATE EXTENSION IF NOT EXISTS ltree WITH SCHEMA public;


--
-- Name: EXTENSION ltree; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION ltree IS 'data type for hierarchical tree-like structures';


--
-- Name: ltree_invarchar(character varying); Type: FUNCTION; Schema: public; Owner: dove
--

CREATE FUNCTION public.ltree_invarchar(character varying) RETURNS public.ltree
    LANGUAGE sql IMMUTABLE
    AS $_$
SELECT ltree_in($1::cstring);
$_$;


ALTER FUNCTION public.ltree_invarchar(character varying) OWNER TO dove;

--
-- Name: CAST (character varying AS public.ltree); Type: CAST; Schema: -; Owner: 
--

CREATE CAST (character varying AS public.ltree) WITH FUNCTION public.ltree_invarchar(character varying) AS IMPLICIT;


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: posto; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.posto (
    id character varying NOT NULL,
    nome character varying,
    percorso public.ltree
);


ALTER TABLE public.posto OWNER TO dove;

--
-- Name: breadcrumbs; Type: VIEW; Schema: public; Owner: dove
--

CREATE VIEW public.breadcrumbs AS
 SELECT (((p.id)::text || '|'::text) || (c.id)::text) AS id,
    c.id AS id_posto,
    p.id AS id_breadcrumb,
    COALESCE(public.nlevel(p.percorso), 0) AS sort
   FROM (public.posto p
     JOIN public.posto c ON (((COALESCE(p.percorso, ''::public.ltree) OPERATOR(public.||) replace((p.id)::text, '-'::text, '_'::text)) OPERATOR(public.@>) (c.percorso OPERATOR(public.||) replace((c.id)::text, '-'::text, '_'::text)))))
  WHERE ((c.id)::text <> (p.id)::text);


ALTER TABLE public.breadcrumbs OWNER TO dove;

--
-- Name: cliente; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.cliente (
    id character varying NOT NULL,
    nome character varying NOT NULL,
    scheda jsonb NOT NULL
);


ALTER TABLE public.cliente OWNER TO dove;

--
-- Name: oggetto; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.oggetto (
    id character varying NOT NULL,
    id_posto character varying,
    scheda jsonb,
    nome character varying,
    thumbnail character varying
);


ALTER TABLE public.oggetto OWNER TO dove;

--
-- Name: oggetto_ordine; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.oggetto_ordine (
    id integer NOT NULL,
    id_oggetto character varying NOT NULL,
    id_ordine character varying NOT NULL,
    stato character varying NOT NULL
);


ALTER TABLE public.oggetto_ordine OWNER TO dove;

--
-- Name: oggetto_ordine_id_seq; Type: SEQUENCE; Schema: public; Owner: dove
--

ALTER TABLE public.oggetto_ordine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oggetto_ordine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordine; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.ordine (
    id character varying NOT NULL,
    id_cliente character varying NOT NULL,
    scheda jsonb NOT NULL,
    stato character varying NOT NULL
);


ALTER TABLE public.ordine OWNER TO dove;

--
-- Name: utente; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.utente (
    id character varying NOT NULL,
    username character varying NOT NULL,
    password character varying,
    hash character varying,
    salt character varying,
    abilitato boolean,
    account_valido boolean,
    credenziali_valide boolean,
    account_attivo boolean
);


ALTER TABLE public.utente OWNER TO dove;

--
-- Name: utente_cliente; Type: TABLE; Schema: public; Owner: dove
--

CREATE TABLE public.utente_cliente (
    id integer NOT NULL,
    id_utente character varying NOT NULL,
    id_cliente character varying NOT NULL
);


ALTER TABLE public.utente_cliente OWNER TO dove;

--
-- Name: utente_cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: dove
--

ALTER TABLE public.utente_cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utente_cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.cliente (id, nome, scheda) FROM stdin;
fe86f172-d353-4d4d-b5ff-8e4331e7b6f8	Cliente di prova	{}
\.


--
-- Data for Name: oggetto; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.oggetto (id, id_posto, scheda, nome, thumbnail) FROM stdin;
4381d2a0-bfa7-4957-b38f-3f8bfb0b1b59	149d624c-2c00-4590-9813-ab0c8ced81ff	{"tipo": "accessorio", "accessorio": "seggiolone-piccoli", "condizioni": 4}	\N	\N
3b7cdae0-ceb5-440c-a2ba-82eca662c77d	149d624c-2c00-4590-9813-ab0c8ced81ff	{"tipo": "scatola", "contenuti": [{"eta": ["6m", "9m", "12m"], "tipo": "vestiti", "sesso": "femmina", "stagione": ["estate"]}, {"eta": ["3a", "4a"], "tipo": "vestiti", "sesso": "femmina", "stagione": ["inverno"]}]}	\N	49650101-3e28-4213-a3e7-ae9aabb76d54
86a3555f-adb0-4750-a5b2-5647b6ce90be	149d624c-2c00-4590-9813-ab0c8ced81ff	{"note": "", "tipo": "accessorio", "accessorio": "passeggino", "condizioni": 4, "descrizione": "Colori pastello"}	\N	ee09a59d-4c5a-466c-8b86-edd72df7906b
0aba0274-4ff5-4489-b5e3-1fc42552ae74	149d624c-2c00-4590-9813-ab0c8ced81ff	{"tipo": "scatola", "contenuti": []}	\N	2e9e5ecb-a537-4465-989c-61d54909c081
f2980be0-5c25-4540-bf07-78c7c2a6bdba	4f3d27be-6b4b-4947-8bdb-565139289a45	{"note": "Do re mi", "tipo": "accessorio", "accessorio": "passeggino-doppio-fila", "condizioni": 4, "descrizione": "passeggino chicco arancio e blu"}	\N	bb3be083-73e8-4934-bb84-949776322265
7c95a126-72ed-48e3-a1ac-70c120244c0d	149d624c-2c00-4590-9813-ab0c8ced81ff	{"tipo": "scatola", "descrizione": "Scatola viola e blue"}	\N	f0442449-5e04-4e9c-a7ec-f64617c50510
\.


--
-- Data for Name: oggetto_ordine; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.oggetto_ordine (id, id_oggetto, id_ordine, stato) FROM stdin;
5	86a3555f-adb0-4750-a5b2-5647b6ce90be	ad11313b-6fa9-4d02-9972-386a5173d9d7	selezionato
\.


--
-- Data for Name: ordine; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.ordine (id, id_cliente, scheda, stato) FROM stdin;
ad11313b-6fa9-4d02-9972-386a5173d9d7	fe86f172-d353-4d4d-b5ff-8e4331e7b6f8	{}	nuovo
\.


--
-- Data for Name: posto; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.posto (id, nome, percorso) FROM stdin;
149d624c-2c00-4590-9813-ab0c8ced81ff	Magazzino	\N
c083e2b8-5472-45f5-a99d-781e9ed97b85	Stanza est	149d624c_2c00_4590_9813_ab0c8ced81ff
5a2efe4c-8066-468b-b5b8-7cba13597c27	Stanza ovest	149d624c_2c00_4590_9813_ab0c8ced81ff
4f3d27be-6b4b-4947-8bdb-565139289a45	Scaffale ovest A	149d624c_2c00_4590_9813_ab0c8ced81ff.5a2efe4c_8066_468b_b5b8_7cba13597c27
\.


--
-- Data for Name: utente; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.utente (id, username, password, hash, salt, abilitato, account_valido, credenziali_valide, account_attivo) FROM stdin;
488bc353-2e1e-4896-9bd3-046230bda005	daniele	cav-01	plain	\N	t	t	t	t
\.


--
-- Data for Name: utente_cliente; Type: TABLE DATA; Schema: public; Owner: dove
--

COPY public.utente_cliente (id, id_utente, id_cliente) FROM stdin;
6	488bc353-2e1e-4896-9bd3-046230bda005	fe86f172-d353-4d4d-b5ff-8e4331e7b6f8
\.


--
-- Name: oggetto_ordine_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dove
--

SELECT pg_catalog.setval('public.oggetto_ordine_id_seq', 5, true);


--
-- Name: utente_cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dove
--

SELECT pg_catalog.setval('public.utente_cliente_id_seq', 6, true);


--
-- Name: cliente cliente_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pk PRIMARY KEY (id);


--
-- Name: oggetto_ordine oggetto_ordine_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.oggetto_ordine
    ADD CONSTRAINT oggetto_ordine_pk PRIMARY KEY (id);


--
-- Name: oggetto_ordine oggetto_ordine_un; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.oggetto_ordine
    ADD CONSTRAINT oggetto_ordine_un UNIQUE (id_oggetto);


--
-- Name: oggetto oggetto_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.oggetto
    ADD CONSTRAINT oggetto_pk PRIMARY KEY (id);


--
-- Name: ordine ordine_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.ordine
    ADD CONSTRAINT ordine_pk PRIMARY KEY (id);


--
-- Name: posto posto_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.posto
    ADD CONSTRAINT posto_pk PRIMARY KEY (id);


--
-- Name: utente_cliente utente_cliente_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.utente_cliente
    ADD CONSTRAINT utente_cliente_pk PRIMARY KEY (id);


--
-- Name: utente utente_pk; Type: CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.utente
    ADD CONSTRAINT utente_pk PRIMARY KEY (id);


--
-- Name: oggetto_ordine oggetto_ordine_fk_oggetto; Type: FK CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.oggetto_ordine
    ADD CONSTRAINT oggetto_ordine_fk_oggetto FOREIGN KEY (id_oggetto) REFERENCES public.oggetto(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: oggetto_ordine oggetto_ordine_fk_ordine; Type: FK CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.oggetto_ordine
    ADD CONSTRAINT oggetto_ordine_fk_ordine FOREIGN KEY (id_ordine) REFERENCES public.ordine(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: ordine ordine_fk; Type: FK CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.ordine
    ADD CONSTRAINT ordine_fk FOREIGN KEY (id_cliente) REFERENCES public.cliente(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: utente_cliente utente_cliente_fk; Type: FK CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.utente_cliente
    ADD CONSTRAINT utente_cliente_fk FOREIGN KEY (id_utente) REFERENCES public.utente(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: utente_cliente utente_cliente_fk_1; Type: FK CONSTRAINT; Schema: public; Owner: dove
--

ALTER TABLE ONLY public.utente_cliente
    ADD CONSTRAINT utente_cliente_fk_1 FOREIGN KEY (id_cliente) REFERENCES public.cliente(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

